# Generated by Django 5.1.3 on 2025-09-04 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EspServer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='online',
        ),
    ]
