# Generated by Django 5.1.3 on 2025-08-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EspServer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensor',
            name='group_name',
            field=models.CharField(default='Inne', max_length=100),
        ),
    ]
