# Generated by Django 5.1.3 on 2025-08-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EspServer', '0002_device_online_sensor_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(default='sensor name', max_length=100),
        ),
    ]
