# Generated by Django 5.1.3 on 2026-02-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EspServer', '0002_remove_device_online'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensordata',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='pin_number',
        ),
        migrations.AddField(
            model_name='sensor',
            name='type_of_sensor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
