# Generated by Django 5.2.5 on 2025-08-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EspServer', '0002_adddevicetoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='online',
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
