# Generated by Django 5.2.5 on 2025-08-28 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EspServer', '0003_remove_device_online_device_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_number', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('pin_function', models.CharField(choices=[('TEMP', 'Czujnik temperatury'), ('SWITCH', 'Wyjście ON/OFF')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='device_config',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EspServer.deviceconfig'),
        ),
    ]
