# Generated by Django 5.1.3 on 2026-02-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EspServer', '0003_alter_sensordata_options_remove_sensor_pin_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
