# Generated by Django 5.2.5 on 2025-08-28 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EspServer', '0004_deviceconfig_device_device_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_config',
        ),
        migrations.AddField(
            model_name='deviceconfig',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='EspServer.device'),
        ),
    ]
