# Generated by Django 5.2.5 on 2025-08-28 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EspServer', '0005_remove_device_device_config_deviceconfig_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceconfig',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='EspServer.device'),
        ),
    ]
