# Generated by Django 5.1.3 on 2026-07-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EspServer', '0005_alter_device_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_battery_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
