# Generated by Django 5.1.3 on 2026-07-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EspServer', '0006_device_last_battery_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='charging',
            field=models.BooleanField(default=False),
        ),
    ]
