# Generated by Django 5.2.5 on 2025-08-28 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EspServer', '0006_alter_deviceconfig_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfig',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pin_config', to='EspServer.sensor'),
        ),
    ]
