# Generated by Django 5.2.5 on 2025-08-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EspServer', '0007_deviceconfig_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='pin_number',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1),
        ),
    ]
