# Generated by Django 5.2.5 on 2025-08-28 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EspServer', '0008_sensor_pin_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device_id',
            new_name='device_serial_number',
        ),
    ]
