# Generated by Django 5.2.5 on 2025-08-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EspServer', '0010_remove_sensordata_sensor_measurementsgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
