# Generated by Django 5.2.5 on 2025-08-29 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EspServer', '0011_device_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='name',
        ),
    ]
