# Generated by Django 5.1.3 on 2025-08-31 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EspServer', '0012_remove_sensor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='measurements_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mg_sensors', to='EspServer.measurementsgroup'),
        ),
    ]
