# Generated by Django 5.2.5 on 2025-09-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EspServer', '0013_alter_sensor_measurements_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='pin_number',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='DeviceConfig',
        ),
    ]
