# Generated by Django 5.2.5 on 2025-09-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EspServer', '0014_alter_sensor_pin_number_delete_deviceconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sensor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
