# Generated by Django 5.2.5 on 2025-09-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EspServer', '0015_sensor_sensor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default='Nadaj nazwę', max_length=100),
        ),
    ]
