# Generated by Django 5.2.5 on 2025-09-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EspServer', '0016_alter_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementsgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
